add linker option --allow-multiple-definition to common.make
(if this comes back to bite us, we will need to resolve this error that was showing:

[ LD ] bm_badge.out
/usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: /usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libstdc++_nano.a(math_stubs_long_double.o): in function `ceill':
math_stubs_long_double.cc:(.text.ceill+0x0): multiple definition of `ceill'; /usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libm.a(lib_a-ceill.o):ceill.c:(.text.ceill+0x0): first defined here
collect2: error: ld returned 1 exit status)